# utilities/swagger.py
swagger_template = {
    "swagger": "2.0",
    "info": {
        "title": "OpenLDR API",
        "description": "This is an API for managing OPENLDR repository.",
        "version": "0.0.1",
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization header using the Bearer scheme. Example: 'Authorization: Bearer {token}'",
        }
    },
    "security": [{"Bearer": []}],
    "host": "localhost:5000",
    "basePath": "/",
    "schemes": ["http", "https"],
    "parameters": {
        "UserLoginParameters": {
            "name": "login",
            "in": "body",
            "schema": {"$ref": "#/definitions/user_login"},
            "required": True,
            "description": "Credentials for user authentication. Must be sent over HTTPS.",
        },
        "UserUpdateParameters": {
            "name": "update",
            "in": "body",
            "schema": {"$ref": "#/definitions/user_update"},
            "required": True,
            "description": "Data for updating a user account. Must be sent over HTTPS.",
        },
        "UserDeletionParameters": {
            "name": "delete",
            "in": "body",
            "schema": {"$ref": "#/definitions/user_deletion"},
            "required": True,
            "description": "The ID of the user to delete.",
        },
        "UserCreateParameters": {
            "name": "create",
            "in": "body",
            "schema": {"$ref": "#/definitions/user_create"},
            "required": True,
            "description": "Data for creating a new user account. Must be sent over HTTPS.",
        },
        "ProvinceParameter": {
            "name": "province",
            "in": "query",
            "type": "array",
            "required": False,
            "items": {
                "type": "string",
                "enum": [
                    "Sofala",
                    "Manica",
                    "Cabo Delgado",
                    "Niassa",
                    "Maputo Provincia",
                    "Nampula",
                    "Gaza",
                    "Inhambane",
                    "Maputo Cidade",
                    "Tete",
                    "Zambezia",
                ],
            },
            "collectionFormat": "multi",
            "description": "The name(s) of the province(s) for which to retrieve all facilities. Multiple provinces can be selected.",
        },
        "DistrictParameter": {
            "name": "district",
            "in": "query",
            "type": "array",
            "required": False,
            "items": {
                "type": "string",
                "enum": [
                    "Muidumbe",
                    "Palma",
                    "Meluco",
                    "Namuno",
                    "Macomia",
                    "Mecufi",
                    "Pemba",
                    "Quissanga",
                    "Mueda",
                    "Ibo",
                    "Ancuabe",
                    "Chiure",
                    "Montepuez",
                    "Nangade",
                    "Metuge",
                    "Balama",
                    "Mocimboa da Praia",
                    "Chicualacuala",
                    "Chongoene",
                    "Bilene Macia",
                    "Mapai",
                    "Chigubo",
                    "Manjacaze",
                    "Mabalane",
                    "Limpopo",
                    "Chokwe",
                    "Chibuto",
                    "Xai-Xai",
                    "Massangena",
                    "Massingir",
                    "Guija",
                    "Vilankulo",
                    "Morrumbene",
                    "Jangamo",
                    "Homoine",
                    "Mabote",
                    "Maxixe",
                    "Panda",
                    "Govuro",
                    "Massinga",
                    "Inhambane",
                    "Inhassoro",
                    "Inharrime",
                    "Funhalouro",
                    "Zavala",
                    "Guro",
                    "Sussundenga",
                    "Manica",
                    "Mossurize",
                    "Vanduzi",
                    "Barue",
                    "Macossa",
                    "Chimoio",
                    "Machaze",
                    "Tambara",
                    "Gondola",
                    "Macate",
                    "Kamaxakeni",
                    "Katembe",
                    "Kamavota",
                    "Nlhamankulu",
                    "Kanyaka",
                    "KaMpfumu",
                    "KaMubukwana",
                    "Namaacha",
                    "Manhica",
                    "Boane",
                    "Moamba",
                    "Magude",
                    "Matola",
                    "Marracuene",
                    "Matutuine",
                    "Nacala Porto",
                    "Angoche",
                    "Nacala Velha",
                    "Mogincual",
                    "Cidade de Nampula",
                    "Muecate",
                    "Ribaue",
                    "Liupo",
                    "Monapo",
                    "Nacaroa",
                    "Larde",
                    "Mecuburi",
                    "Malema",
                    "Memba",
                    "Namapa-Erati",
                    "Moma",
                    "Mossuril",
                    "Murrupula",
                    "Lalaua",
                    "Mogovolas",
                    "Ilha de Mocambique",
                    "Meconta",
                    "Rapale",
                    "Lago",
                    "Mecanhelas",
                    "Majune",
                    "Muembe",
                    "Nipepe",
                    "Mecula",
                    "Ngauma",
                    "Chimbonila",
                    "Marrupa",
                    "Cidade de Lichinga",
                    "Cuamba",
                    "Metarica",
                    "Mavago",
                    "Maua",
                    "Sanga",
                    "Mandimba",
                    "Nhamatanda",
                    "Dondo",
                    "Chemba",
                    "Cheringoma",
                    "Buzi",
                    "Beira",
                    "Chibabava",
                    "Gorongoza",
                    "Muanza",
                    "Maringue",
                    "Marromeu",
                    "Machanga",
                    "Caia",
                    "Mutarara",
                    "Tsangano",
                    "Moatize",
                    "Zumbo",
                    "Angonia",
                    "Changara",
                    "Cahora Bassa",
                    "Maravia",
                    "Magoe",
                    "Tete",
                    "Doa",
                    "Chifunde",
                    "Macanga",
                    "Marara",
                    "Chiuta",
                    "Derre",
                    "Inhassunge",
                    "Lugela",
                    "Gurue",
                    "Alto Molocue",
                    "Maganja da Costa",
                    "Nicoadala",
                    "Morrumbala",
                    "Molumbo",
                    "Luabo",
                    "Gile",
                    "Mopeia",
                    "Pebane",
                    "Milange",
                    "Ile",
                    "Namarroi",
                    "Namacurra",
                    "Mocuba",
                    "Quelimane",
                    "Mulevala",
                    "Chinde",
                    "Mocubela",
                ],
            },
            "collectionFormat": "multi",
            "description": "The name(s) of the district(s) for which to retrieve all facilities. Multiple districts can be selected.",
        },
        "HealthFacilityParameter": {
            "name": "health_facility",
            "in": "query",
            "type": "string",
            "required": False,
            "description": "The name of the health facility to filter by (optional).",
        },
        "LabTypeParameter": {
            "name": "lab_type",
            "in": "query",
            "type": "string",
            "required": False,
            "description": "The type of laboratory to filter by (optional).",
            "enum": [
                "Clinical Only",
                "Cytology",
                "Data Repository",
                "Environmental",
                "General",
                "Histology",
                "Point of care",
                "Postmortem",
                "TB",
                "Trials",
                "VL/EID",
            ],
        },
        "IntervalDates": {
            "name": "interval_dates",
            "in": "query",
            "type": "array",
            "required": False,
            "description": "The date range to filter by (optional).",
            "items": {"type": "string", "format": "date"},
            "example": ["2024-01-01", "2025-01-01"],
            "default": ["2024-01-01", "2025-01-01"],
        },
        "DisaggregationParameter": {
            "name": "disaggregation",
            "in": "query",
            "type": "string",
            "required": False,
            "description": "Whether to include or exclude disaggregated data (optional).",
            "enum": ["True", "False"],
        },
        "FacilityType": {
            "name": "facility_type",
            "in": "query",
            "type": "string",
            "required": False,
            "description": "The type of facility to filter by (optional).",
            "enum": ["province", "district", "health_facility"],
        },
        "GeneXpertResultType": {
            "name": "genexpert_result_type",
            "in": "query",
            "type": "string",
            "required": False,
            "description": "The type of result to filter by (GeneXpert or Xpert).",
            "enum": ["Ultra 6 Cores", "XDR 10 Cores"],
        },
        "TypeOfLaboratory": {
            "name": "type_of_laboratory",
            "in": "query",
            "type": "string",
            "required": False,
            "description": "The type of facility to filter by (optional).",
            "enum": ["Conventional", "Point_Of_Care", "All"],
        },
        "DrugTypeParameter": {
            "name": "drug",
            "in": "query",
            "type": "string",
            "required": False,
            "description": "The type of drug to filter by (optional).",
            "enum": [
                "Rifampicin",
                "Isoniazid",
                "Fluoroquinolona",
                "Kanamicin",
                "Capreomicin",
                "Amikacina",
                "Ethionamida",
            ],
        },
        "ConventionalLaboratories": {
            "name": "conventional_laboratories",
            "in": "query",
            "type": "array",
            "required": False,
            "description": "The name(s) of the conventional laboratories. Multiple conventional laboratories can be selected.",
            "items": {
                "type": "string",
                "enum": [
                    "PBT",
                    "PCA",
                    "PCH",
                    "PCM",
                    "PDM",
                    "PIC",
                    "PIT",
                    "PJC",
                    "PJT",
                    "PLC",
                    "PMA",
                    "PMT",
                    "PNC",
                    "PNT",
                    "PPC",
                    "PPG",
                    "PPI",
                    "PPM",
                    "PQA",
                    "PQC",
                    "PQM",
                    "PTB",
                    "PTC",
                    "PTT",
                    "PXA",
                ],
            },
            "collectionFormat": "multi",
            "example": ["PCA", "PCH", "PCM", "PDM", "PMT", "PMA"],
        },
        "PointOfCareLaboratories": {
            "name": "point_of_care_laboratories",
            "in": "query",
            "type": "array",
            "required": False,
            "description": "The name(s) of the point of care laboratories. Multiple point of care laboratories can be selected.",
            "items": {
                "type": "string",
                "enum": [
                    "CS Bagamoio",
                    "CS Mavalane",
                    "CS Munhava",
                    "HD Caia",
                    "CS Pebane-Sede",
                    "CS Mopeia-Sede",
                    "CS Mocuba",
                    "CS ILE-Sede",
                    "CS Nicoadala-Sede",
                    "HD Moma",
                    "CS Namialo",
                    "CS 25 De Setembro(Nampula)",
                    "CS Nametil",
                    "CS Natite",
                    "CS Namacurra-Sede",
                    "CS Maganja da Costa",
                    "HR Angoche",
                    "CS Muhala-Expansao",
                    "HR Montepuez",
                    "CS Malema",
                    "CS Mecuburi",
                    "CS Maquival Sede",
                    "CS Mocubela",
                    "CS Derre",
                    "CS Inhassunge-Sede",
                    "CS Lugela-Sede(Lugela)",
                    "CS Maxixe",
                    "HC Maputo",
                    "CS Machava II",
                    "CS Ponta Gea",
                    "CS Ancuabe",
                    "CS Namuno",
                    "CS Chongoene",
                    "CS Chissano",
                    "HR Alto Mulocue",
                    "HD Gurue",
                    "CS Milange",
                    "CS Morrumbala",
                    "HG Marrere",
                    "CS Alto Mae",
                    "CS Matola II",
                    "HD Nacala Porto",
                    "HD Mocuba",
                    "HD Milange",
                    "CS Guro-Sede",
                    "CS Macate",
                    "CS Metarica",
                    "CS Massangulo",
                    "CS Inhamizua",
                    "CS Militar de Matacuane",
                    "CS Molumbo",
                ],
            },
            "collectionFormat": "multi",
            "example": [],
        },
    },
    "definitions": {
        "Facilities": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "FacilityName": {"type": "string"},
                    "FacilityCode": {"type": "string"},
                    "FacilityType": {"type": "string"},
                    "FacilityNationalCode": {"type": "string"},
                    "ProvinceName": {"type": "string"},
                    "DistrictName": {"type": "string"},
                    "HFStatus": {"type": "integer"},
                    "Latitude": {"type": "string"},
                    "Longitude": {"type": "string"},
                },
            },
            "description": "A list of facilities with their details.",
        },
        "user_login": {
            "type": "object",
            "required": ["username", "password"],
            "properties": {
                "username": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 50,
                    "example": "johndoe",
                    "description": "The username of the user logging in.",
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "maxLength": 100,
                    "format": "password",
                    "example": "password123",
                    "description": "The password of the user logging in. Must be sent over HTTPS.",
                },
            },
        },
        "user_update": {
            "type": "object",
            "required": [
                "user_id",
                "username",
                "first_name",
                "last_name",
                "email",
                "role",
            ],
            "properties": {
                "user_id": {
                    "type": "string",
                    "minLength": 6,
                    "maxLength": 100,
                    "example": "1234567890",
                    "description": "The ID of the user to update.",
                },
                "username": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 50,
                    "example": "johndoe",
                    "description": "The new username of the user.",
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "maxLength": 100,
                    "format": "password",
                    "example": "newpassword123",
                    "description": "The new password of the user. Optional. Must be sent over HTTPS.",
                },
                "confirm_password": {
                    "type": "string",
                    "minLength": 6,
                    "maxLength": 100,
                    "format": "password",
                    "example": "newpassword123",
                    "description": "The confirmation of the new password. Optional. Must match the password field if provided.",
                },
                "role": {
                    "type": "string",
                    "enum": ["admin", "user"],
                    "example": "user",
                    "description": "The role of the user (admin or user).",
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "johndoe@example.com",
                    "description": "The email address of the user.",
                },
                "first_name": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50,
                    "example": "John",
                    "description": "The first name of the user.",
                },
                "last_name": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50,
                    "example": "Doe",
                    "description": "The last name of the user.",
                },
            },
        },
        "user_create": {
            "type": "object",
            "required": [
                "username",
                "first_name",
                "last_name",
                "password",
                "confirm_password",
                "email",
                "role",
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 50,
                    "example": "johndoe",
                    "description": "The new username of the user.",
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "maxLength": 100,
                    "format": "password",
                    "example": "newpassword123",
                    "description": "The new password of the user. Optional. Must be sent over HTTPS.",
                },
                "confirm_password": {
                    "type": "string",
                    "minLength": 6,
                    "maxLength": 100,
                    "format": "password",
                    "example": "newpassword123",
                    "description": "The confirmation of the new password. Optional. Must match the password field if provided.",
                },
                "role": {
                    "type": "string",
                    "enum": ["admin", "user"],
                    "example": "user",
                    "description": "The role of the user (admin or user).",
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "johndoe@example.com",
                    "description": "The email address of the user.",
                },
                "first_name": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50,
                    "example": "John",
                    "description": "The first name of the user.",
                },
                "last_name": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50,
                    "example": "Doe",
                    "description": "The last name of the user.",
                },
            },
        },
        "user_deletion": {
            "type": "object",
            "required": ["user_id"],
            "properties": {
                "user_id": {
                    "type": "string",
                    "minLength": 6,
                    "maxLength": 100,
                    "example": "1234567890",
                    "description": "The ID of the user to delete.",
                },
            },
        },
    },
}
