import os

# Flask App Secret
SECRET_KEY = os.environ.get("FLASK_SECRET_KEY", "default-secret-key")

# Domain Paths
LOCAL_DOMAIN_NAME = os.environ.get("LOCAL_DOMAIN")
CDR_DOMAIN_NAME = os.environ.get("CDR_DOMAIN")
CLOUD_DOMAIN_NAME = os.environ.get("CLOUD_DOMAIN")

# Database Names
VIRALLOADDATA_DATABASE = os.environ.get("DB_VL_DATA")
VIRALLOADSMS_DATABASE = os.environ.get("DB_VL_SMS")
DPI_DATABASE_DATABASE = os.environ.get("DB_DPI")
HIVAD_DATABASE = os.environ.get("DB_HIV_AD")
TBDATA_DATABASE_DATABASE = os.environ.get("DB_TB_DATA")
DICT_DATABASE_DATABASE = os.environ.get("DB_DICT")
USER_DATABASE = os.environ.get("DB_USERS")

# Database Credentials
USERNAME = os.environ.get("DB_USER")
PASSWORD = os.environ.get("DB_PASSWORD")

# Schemas
CDR_DOMAIN_NAME_SCHEMA = os.environ.get("SCHEMA_CDR")


# SQLAlchemy Connection Strings
def make_url(user, pwd, host, db):
    return (
        f"mssql+pyodbc://{user}:{pwd}@{host}/{db}?driver=ODBC+Driver+17+for+SQL+Server"
    )


SQLALCHEMY_BINDS_APHL_OPENLDR_ORG_MZ = {
    "vlSMS": make_url(USERNAME, PASSWORD, LOCAL_DOMAIN_NAME, VIRALLOADSMS_DATABASE),
    "vl": make_url(USERNAME, PASSWORD, LOCAL_DOMAIN_NAME, VIRALLOADDATA_DATABASE),
    "dpi": make_url(USERNAME, PASSWORD, LOCAL_DOMAIN_NAME, DPI_DATABASE_DATABASE),
    "ad": make_url(USERNAME, PASSWORD, LOCAL_DOMAIN_NAME, HIVAD_DATABASE),
    "tb": make_url(USERNAME, PASSWORD, CDR_DOMAIN_NAME, TBDATA_DATABASE_DATABASE),
    "dict": make_url(USERNAME, PASSWORD, LOCAL_DOMAIN_NAME, DICT_DATABASE_DATABASE),
    "users": make_url(USERNAME, PASSWORD, LOCAL_DOMAIN_NAME, USER_DATABASE),
}

SQLALCHEMY_BINDS_CDR_OPENLDR_ORG_MZ = {
    "vl": make_url(USERNAME, PASSWORD, CDR_DOMAIN_NAME, VIRALLOADDATA_DATABASE),
    "dpi": make_url(USERNAME, PASSWORD, CDR_DOMAIN_NAME, DPI_DATABASE_DATABASE),
    "ad": make_url(USERNAME, PASSWORD, CDR_DOMAIN_NAME, HIVAD_DATABASE),
    "tb": make_url(USERNAME, PASSWORD, CDR_DOMAIN_NAME, TBDATA_DATABASE_DATABASE),
    "dict": make_url(USERNAME, PASSWORD, CDR_DOMAIN_NAME, DICT_DATABASE_DATABASE),
    "users": make_url(USERNAME, PASSWORD, CDR_DOMAIN_NAME, USER_DATABASE),
}

SQLALCHEMY_BINDS_CLOUD_QUEUE_OPENLDR_ORG_MZ = {
    "vl": make_url(USERNAME, PASSWORD, CLOUD_DOMAIN_NAME, VIRALLOADDATA_DATABASE),
    "dpi": make_url(USERNAME, PASSWORD, CLOUD_DOMAIN_NAME, DPI_DATABASE_DATABASE),
    "ad": make_url(USERNAME, PASSWORD, CLOUD_DOMAIN_NAME, HIVAD_DATABASE),
    "tb": make_url(USERNAME, PASSWORD, CLOUD_DOMAIN_NAME, TBDATA_DATABASE_DATABASE),
    "dict": make_url(USERNAME, PASSWORD, CLOUD_DOMAIN_NAME, DICT_DATABASE_DATABASE),
    "users": make_url(USERNAME, PASSWORD, CLOUD_DOMAIN_NAME, USER_DATABASE),
}
