# import db from db.database.py
from db.database import db


class VlData(db.Model):
    __bind_key__ = "vlSMS"
    __tablename__ = "VlData"
    __table_args__ = {"extend_existing": True}

    id = db.Column(db.Integer, primary_key=True)
    RequestID = db.Column(db.String(26))
    Versionstamp = db.Column(db.String(30))
    REFNO = db.Column(db.String(56))
    REGISTEREDDATE = db.Column(db.DateTime)
    LOCATION = db.Column(db.String(5))
    WARD = db.Column(db.String(5))
    HOSPID = db.Column(db.String(26))
    NATIONALITY = db.Column(db.String(5))
    NATIONALID = db.Column(db.String(26))
    UNIQUEID = db.Column(db.String(31))
    SURNAME = db.Column(db.String(31))
    FIRSTNAME = db.Column(db.String(31))
    INITIALS = db.Column(db.String(16))
    REFDRCODE = db.Column(db.String(5))
    REFDR = db.Column(db.String(41))
    MEDAID = db.Column(db.String(5))
    MEDAIDNO = db.Column(db.String(26))
    BILLACCNO = db.Column(db.String(23))
    TELHOME = db.Column(db.String(20))
    TELWORK = db.Column(db.String(20))
    MOBILE = db.Column(db.String(20))
    EMAIL = db.Column(db.String(60))
    DOB = db.Column(db.Date)
    DOBType = db.Column(db.String(25))
    AgeInDays = db.Column(db.Integer)
    HL7SexCode = db.Column(db.String(1))
    SpecimenDatetime = db.Column(db.DateTime)
    ReceivedDateTime = db.Column(db.DateTime)
    RegisteredDateTime = db.Column(db.DateTime)
    AnalysisDateTime = db.Column(db.DateTime)
    AuthorisedDateTime = db.Column(db.DateTime)
    LIMSRejectionCode = db.Column(db.String(10))
    LIMSRejectionDesc = db.Column(db.String(250))
    LIMSDateTimeStamp = db.Column(db.DateTime)
    Newborn = db.Column(db.Boolean)
    Pregnant = db.Column(db.String(80), nullable=False)
    BreastFeeding = db.Column(db.String(80), nullable=False)
    FirstTime = db.Column(db.String(80), nullable=False)
    CollectedDate = db.Column(db.String(80))
    CollectedTime = db.Column(db.String(80))
    DataDeInicioDoTARV = db.Column(db.String(80))
    PrimeiraLinha = db.Column(db.String(80), nullable=False)
    SegundaLinha = db.Column(db.String(80), nullable=False)
    ARTRegimen = db.Column(db.String(80), nullable=False)
    TypeOfSampleCollection = db.Column(db.String(80), nullable=False)
    LastViralLoadDate = db.Column(db.String(80), nullable=False)
    LastViralLoadResult = db.Column(db.String(80), nullable=False)
    RequestingClinician = db.Column(db.String(80), nullable=False)
    LIMSVersionstamp = db.Column(db.String(30))
    LOINCPanelCode = db.Column(db.String(10))
    HL7PriorityCode = db.Column(db.String(1))
    AdmitAttendDateTime = db.Column(db.DateTime)
    CollectionVolume = db.Column(db.Float)
    LIMSFacilityCode = db.Column(db.String(15))
    LIMSFacilityName = db.Column(db.String(50))
    LIMSProvinceName = db.Column(db.String(50))
    LIMSDistrictName = db.Column(db.String(50))
    RequestingFacilityCode = db.Column(db.String(15))
    RequestingFacilityName = db.Column(db.String(50))
    RequestingProvinceName = db.Column(db.String(50))
    RequestingDistrictName = db.Column(db.String(50))
    ReceivingFacilityCode = db.Column(db.String(10))
    ReceivingFacilityName = db.Column(db.String(50))
    ReceivingProvinceName = db.Column(db.String(50))
    ReceivingDistrictName = db.Column(db.String(50))
    TestingFacilityCode = db.Column(db.String(10))
    TestingFacilityName = db.Column(db.String(50))
    TestingProvinceName = db.Column(db.String(50))
    TestingDistrictName = db.Column(db.String(50))
    LIMSPointOfCareDesc = db.Column(db.String(50))
    RequestTypeCode = db.Column(db.String(3))
    ICD10ClinicalInfoCodes = db.Column(db.String(50))
    ClinicalInfo = db.Column(db.String(250))
    HL7SpecimenSourceCode = db.Column(db.String(10))
    LIMSSpecimenSourceCode = db.Column(db.String(10))
    LIMSSpecimenSourceDesc = db.Column(db.String(50))
    HL7SpecimenSiteCode = db.Column(db.String(10))
    LIMSSpecimenSiteCode = db.Column(db.String(10))
    LIMSSpecimenSiteDesc = db.Column(db.String(50))
    WorkUnits = db.Column(db.Float)
    CostUnits = db.Column(db.Float)
    HL7SectionCode = db.Column(db.String(3))
    HL7ResultStatusCode = db.Column(db.String(1))
    RegisteredBy = db.Column(db.String(250))
    TestedBy = db.Column(db.String(250))
    AuthorisedBy = db.Column(db.String(250))
    OrderingNotes = db.Column(db.String(250))
    EncryptedPatientID = db.Column(db.String(255))
    HL7EthnicGroupCode = db.Column(db.String(3))
    Deceased = db.Column(db.Boolean)
    HL7PatientClassCode = db.Column(db.String(1))
    AttendingDoctor = db.Column(db.String(50))
    ReferringRequestID = db.Column(db.String(25))
    Therapy = db.Column(db.String(250))
    LIMSAnalyzerCode = db.Column(db.String(10))
    TargetTimeDays = db.Column(db.Integer)
    TargetTimeMins = db.Column(db.Integer)
    Repeated = db.Column(db.Integer)
    HIVVL_AuthorisedDateTime = db.Column(db.DateTime)
    HIVVL_LIMSRejectionCode = db.Column(db.String(10))
    HIVVL_LIMSRejectionDesc = db.Column(db.String(250))
    HIVVL_VRLogValue = db.Column(db.String(80))
    ViralLoadResultCategory = db.Column(db.String(1024))
    HIVVL_ViralLoadResult = db.Column(db.String(80))
    HIVVL_ViralLoadCAPCTM = db.Column(db.String(80))
    AgeGroup = db.Column(db.String(64))
    AgeInYears = db.Column(db.Integer)
    ReasonForTest = db.Column(db.String(64), nullable=False)
    RegisteredYearAndQuarter = db.Column(db.String(25), nullable=False)
    RegisteredYearAndMonth = db.Column(db.String(25), nullable=False)
    DateTimeStamp = db.Column(db.DateTime)
    HealthCareID = db.Column(db.String(20))
    FullFacilityCode = db.Column(db.String(50))
    EPTS = db.Column(db.String(255))
    EPTS_DATETIME = db.Column(db.DateTime)
    CentralServer = db.Column(db.String(50))
    CentralServerDatetime = db.Column(db.DateTime)
    HealthcareNo = db.Column(db.String(255))
    LIMSPreReg_RegistrationDateTime = db.Column(db.DateTime)
    LIMSPreReg_ReceivedDateTime = db.Column(db.DateTime)
    LIMSPreReg_RegistrationFacilityCode = db.Column(db.String(100))
    CreatedAt = db.Column(db.DateTime)
    Latitude = db.Column(db.String(100))
    Longitude = db.Column(db.String(100))
    RequestingFacilityNationalCode = db.Column(db.String(100))
    FinalViralLoadResult = db.Column(db.String(100))
    IsDisaLink = db.Column(db.Boolean)
    IsDisaPoc = db.Column(db.Boolean)
    SMS_NOTIFICATION = db.Column(db.String(100))
    SMS_NOTIFICATION_DATETIME = db.Column(db.DateTime)
    PatientNotification = db.Column(db.String(100))
    FacilityNotification = db.Column(db.String(100))
    PatientNotifiedAt = db.Column(db.DateTime)
    FacilityNotifiedAt = db.Column(db.DateTime)
    PatientNotificationDelivery = db.Column(db.String(100))
    FacilityNotificationDelivery = db.Column(db.String(100))
    PatientNotificationDeliveredAt = db.Column(db.DateTime)
    FacilityNotificationDeliveredAt = db.Column(db.DateTime)
    SmsAttempts = db.Column(db.Integer)

    # No pagination decorator or functionality added in this example
    # Flask-SQLAlchemy handles the database interaction, pagination can be managed with other methods


# To use VlData model, you would import it in your main app and initialize with Flask app instance like below:
# from your_module import db, VlData
# app = Flask(__name__)
# app.config['SQLALCHEMY_DATABASE_URI'] = 'your-database-url'
# db.init_app(app)
